### ISSUE TITLE
Compilation fails under C++17

### ISSUE THREAD

**Issue by petrmanek** [EPC-MSU/Bindy#3]
Hi, I am trying to compile Bindy with `CMAKE_CXX_STANDARD=17`. Currently the process is not successful because the `sole` submodule is checked out at [a 7 years old version](https://github.com/r-lyeh-archived/sole/tree/811f6925067c75340cbb7c633d99691977553866). Because of that, the library is really not ready for the new standard and uses deprecated symbols causing the following compilation error:

```
In file included from /tmp/xibridge/vendor/bindy/vendor/sole/sole.cpp:1:
/tmp/xibridge/vendor/bindy/vendor/sole/sole.hpp:92:44: error: ‘template<class _Arg, class _Result> struct std::unary_function’ is deprecated [-Werror=deprecated-declarations]
   92 |     class hash< sole::uuid > : public std::unary_function< sole::uuid, size_t > {
      |                                            ^~~~~~~~~~~~~~
In file included from /usr/include/c++/13.2.1/functional:49,
                 from /tmp/xibridge/vendor/bindy/vendor/sole/sole.hpp:49:
/usr/include/c++/13.2.1/bits/stl_function.h:117:12: note: declared here
  117 |     struct unary_function
      |            ^~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

Fortunately, there has been a [PR correcting this very problem](https://github.com/r-lyeh-archived/sole/pull/21) in the upstream repo, so all that has to be done is to bump the submodule to at least [this commit](https://github.com/r-lyeh-archived/sole/tree/ca1122303face1176b4c9595371f6b0019538cd4) or newer. Locally I have verified that this permits the compilation to finish successfully. No idea, though, whether that impact the behavior of the code in any meaningful way.

**Comment by shampletov-no** [comment]
Hi Petr

Thank you for noticing this bug. It originates from a fact that we haven't tested the project with C++ newer than C++11. And now we are working on it.

By the way, there is another interesting thing. While we trying to repeat your problem, we face cryptopp bug of `byte` ambiguity. It was solved [here](https://github.com/weidai11/cryptopp/commit/00f9818b5d8e) in original cryptopp repository, but not in our fork. So we wonder, how could you avoid the problem? Did you change our cryptopp to the original one? And can you provide us with info about your compilator?

cryptopp bug fragment:
```
/home/xiuser/projects/xibridge/vendor/bindy/vendor/cryptopp/asn.cpp:22:10: error: reference to ‘byte’ is ambiguous
   22 |   bt.Put(byte(length));
      |          ^~~~
In file included from /home/xiuser/projects/xibridge/vendor/bindy/vendor/cryptopp/stdcpp.h:48,
                 from /home/xiuser/projects/xibridge/vendor/bindy/vendor/cryptopp/cryptlib.h:87,
                 from /home/xiuser/projects/xibridge/vendor/bindy/vendor/cryptopp/asn.h:9,
                 from /home/xiuser/projects/xibridge/vendor/bindy/vendor/cryptopp/asn.cpp:8:
/usr/include/c++/9/cstddef:69:14: note: candidates are: ‘enum class std::byte’
   69 |   enum class byte : unsigned char {};
      |              ^~~~
In file included from /home/xiuser/projects/xibridge/vendor/bindy/vendor/cryptopp/pch.h:13,
                 from /home/xiuser/projects/xibridge/vendor/bindy/vendor/cryptopp/asn.cpp:3:
/home/xiuser/projects/xibridge/vendor/bindy/vendor/cryptopp/config.h:230:23: note:                 ‘typedef unsigned char byte’
  230 | typedef unsigned char byte;  // put in global namespace to avoid ambiguity with other byte typedefs
      |                       ^~~~
```

**Comment by shampletov-no** [comment]
Hi Petr

We decided to stay on the old versions of `sole` (and `cryptopp`). Why? It turned out that the new versions are incompatible with some of our old devices, which we ought to maintain :(

**Comment by petrmanek** [comment]
Apologies for a delayed response. Christmas break caught up with me. Please see my responses below.

> So we wonder, how could you avoid the problem? Did you change our cryptopp to the original one?

I did not see this particular error on my system. I am currently compiling Bindy at 319480ae410ab7106859aa733ee38eff36e23c4e and cryptopp at 7994185129969c78e751f16f52bb0be1982504f0. Note that I made no changes to cryptopp -- these revisions were checked out automatically with `git clone --recursive`.


> And can you provide us with info about your compilator?

Sure, I am using gcc (GCC) 13.2.1 20230801. I also tried clang 16.0.6 without any observable difference.


> It turned out that the new versions are incompatible with some of our old devices, which we ought to maintain :(

Just to be sure, can you please clarify which devices are affected by my proposed fix? For the record, I am testing locally with `8SMC5-USB-B9-2` controller.

Finally, can you please advise what toolchain (compiler, standard library, flags) I should use in order to successfully compile Bindy in the current state? Thus far I was unable to compile it successfully without addressing the problem I described in my initial message. Thank you!

**Comment by shampletov-no** [comment]
> Just to be sure, can you please clarify which devices are affected by my proposed fix?

I was a little inaccurate about incompatibility _with old devices_. Actually, it is incompatibility with _old OS_, that runs on our old single-board computers (the "old devices") used as CI servers. We want to build binaries on such an old OS because it gives us confidence that those binaries can be used both on modern systems and old ones. If we switch the old OS for the new one, we may lose backward compatibility and so fail some of our customers.

> can you please advise what toolchain I should use in order to successfully compile Bindy?

You can use your gcc 13.2 without passing `CMAKE_CXX_STANDARD=17` to cmake. Bindy's `CMakeLists.txt` will automatically detect C++11 support and use `-std=c++11` flag.

**Comment by petrmanek** [comment]
> You can use your gcc 13.2 without passing CMAKE_CXX_STANDARD=17 to cmake. Bindy's CMakeLists.txt will automatically detect C++11 support and use -std=c++11 flag.

I have just tried again with the following arguments passed to cmake:

```
-DBUILD_TEST=OFF
-DBUILD_XIBRIDGE_EXAMPLE=OFF
-DBUILD_SHARED_LIBS=ON
-DCMAKE_POSITION_INDEPENDENT_CODE=ON
-DCMAKE_C_STANDARD=11
-DCMAKE_C_STANDARD_REQUIRED=ON
-DCMAKE_CXX_STANDARD=11
-DCMAKE_CXX_STANDARD_REQUIRED=ON
```

And I saw the same about `std::unary_function` being deprecated. Note that I have verified that I am using the correct standard by inspecting the command that fails:

```
/usr/bin/c++ -DBINDY_EXPORTS -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_OMIT_LOAD_EXTENSION -DZF_LOG_LEVEL=ZF_LOG_DEBUG -Dbindy_EXPORTS -I/tmp/project/lib/ep-xibridge-src/vendor/bindy/vendor -I/tmp/project/lib/ep-xibridge-src/vendor/bindy/vendor/cryptopp -I/tmp/project/lib/ep-xibridge-src/vendor/zf_log/zf_log -std=c++11 -std=c++11 -std=gnu++11 -fPIC   -Wno-stringop-overflow -Wall -Wextra -Werror -MD -MT vendor/bindy/CMakeFiles/bindy.dir/bindy.cpp.o -MF vendor/bindy/CMakeFiles/bindy.dir/bindy.cpp.o.d -o vendor/bindy/CMakeFiles/bindy.dir/bindy.cpp.o -c /tmp/project/lib/ep-xibridge-src/vendor/bindy/bindy.cpp
```

I suppose the problem is not caused by the new standard anymore, but rather by the `-Werror` declaration which turns a deprecation warning into an insurmountable error. I tried to track this down in your code base, and found that this option is explicitly enabled [here](https://github.com/EPC-MSU/xibridge/blob/4d1b42e22ab78c1d85acbe5bf05f42b19a9d7dd3/CMakeLists.txt#L108). Even if the scope qualifier is set to `PRIVATE`, any headers included by Bindy's compilation units cannot emit warnings without disrupting the compilation. Looking back at the error message, this is exactly consistent with what the compiler says:

1. `bindy.cpp:30` incudes `sole.hpp`
2. At `sole.hpp:92` there is a `deprecated-declarations` warning since C++11, which is treated as error thanks to `-Werror=deprecated-declarations`

I would be curious as to why your toolchain does not produce a similar behavior. Since you are using C++11, you should be seeing the same warning. And since the project turns on `-Werror` that should lead to an error during compilation. What gives?

As a temporary workaround, I found that adding `-DCMAKE_CXX_FLAGS="-Wno-error=deprecated-declarations"` suppresses the error without addressing the root cause, or having to check out a more recent version of libsole.

**Comment by petrmanek** [comment]
One more quick observation: If you try building Bindy directly, this error does not appear. You can see the deprecation warning, but `-Werror` is not enabled. It only appears when Bindy is included by XiBridge.

**Comment by shampletov-no** [comment]
It seems there is a quick solution - use g++-10. If you use Ubuntu-like system, just try
```shell
apt install g++-10
```
Then find the paths of installed binaries (`/usr/bin/gcc-10` and `/usr/bin/g++-10` in my case). And finally, export CC and CXX before running cmake:
```
export CC=/usr/bin/gcc-10
export CXX=/usr/bin/g++-10
```

---

Why does it help? For reasons known only to God, g++ of version less than 10 ignores the fact that `std::unary_function` is deprecated since C++11... That's why I haven't faced any sole compilation errors (my machine uses g++-9 and our single-board computers use even older g++s).

We'll figure out whether it's safe to use a more recent sole commit. If it is, we will use it. Otherwise, we will figure out something else :)
